#datasource settings
spring:
  datasource:
    url : 'jdbc:h2:file:~/sampleDB'
    driverClassName : 'org.h2.Driver'
    username : 'sa'
    password : ''
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  main:
    banner-mode: off

task.template.allowMultipleTask : false
