#datasource settings
spring:
  datasource:
    url : 'jdbc:h2:file:~/sampleDB'
    driverClassName : 'org.h2.Driver'
    username : 'sa'
    password : ''
  h2:
    console:
      enabled: true
      path: '/h2'
      settings:
        trace: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  main:
    banner-mode: off

task.template.allowMultipleTask : false
